GO
CREATE DATABASE EDUCBTAOFICIAL
GO
USE EDUCBTAOFICIAL
GO


/*---------------------------------------------------TABLAS PRYMARYS*/
CREATE TABLE TBL_TIPO_ROL(
ID_TIPO_ROL INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_TIPO_ROL VARCHAR(30)NOT NULL UNIQUE
)

INSERT INTO TBL_TIPO_ROL (NOMBRE_TIPO_ROL) VALUES
    ('ADMINISTRADOR'),
    ('ALUMNO'),
    ('DOCENTE'),
    ('FAMILIAR'),
	('PRUEBA');
	('DOCENTE TUTORADO')

	SELECT * FROM TBL_TIPO_ROL


CREATE TABLE TBL_SEXOS(
ID_SEXOS INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_SEXO VARCHAR(30)NOT NULL UNIQUE
)
INSERT INTO TBL_SEXOS (NOMBRE_SEXO) VALUES
    ('MASCULINO'),
    ('FEMENINO');

CREATE TABLE TBL_ACTIVOS_CUENTA(
ID_ACTIVOS_CUENTA INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_ACTIVOS_CUENTA VARCHAR(30)NOT NULL UNIQUE
)

INSERT INTO TBL_ACTIVOS_CUENTA (NOMBRE_ACTIVOS_CUENTA) VALUES
    ('ACTIVO'),
    ('BLOQUEADA');

CREATE TABLE TBL_TRASLADO(
ID_TRASLADO INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_TRASLADO VARCHAR(20)NOT NULL UNIQUE
)
INSERT INTO TBL_TRASLADO(NOMBRE_TRASLADO) VALUES
    ('VIAJAS'),
    ('RENTAS');

CREATE TABLE TBL_TRASLADO_TRANSPORTE(
ID_TRASLADO_TRANSPORTE INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_TRASLADO_TRANSPORTE VARCHAR(20)NOT NULL UNIQUE
)

INSERT INTO TBL_TRASLADO_TRANSPORTE(NOMBRE_TRASLADO_TRANSPORTE) VALUES
    ('CAMINANDO'),('MICROBUS'),('URBAN'),('MOTOCICLETA'),('TAXI'),('AUTOMOVIL PRIVADO'),
    ('BICICLETA');

CREATE TABLE TBL_ASIGNATURAS(
ID_ASIGNATURA INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_ASIGNATURA VARCHAR(40)NOT NULL UNIQUE
)
INSERT INTO TBL_ASIGNATURAS(NOMBRE_ASIGNATURA) VALUES
    ('ESPAÑOL'),('MATEMATICAS'),('CIENCIAS'),('PSICOLOGIA'),('EOYE'),('HISTORIA'),
    ('EDUCACION FISICA');

CREATE TABLE TBL_GRADOS(
ID_GRADO INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_GRADO INT NOT NULL UNIQUE
)
INSERT INTO TBL_GRADOS(NOMBRE_GRADO) VALUES
    (1),(2),(3),(4),(5),(6);

CREATE TABLE TBL_GRUPOS(
ID_GRUPOS INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_GRUPOS VARCHAR(3)NOT NULL UNIQUE
)
INSERT INTO TBL_GRUPOS(NOMBRE_GRUPOS) VALUES
    ('A'),('B'),('C'),('D'),('E'),('F'),('G'),('H');

CREATE TABLE TBL_PREGUNTAS(
ID_PREGUNTAS INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_PREGUNTAS VARCHAR(100)NOT NULL UNIQUE
)

INSERT INTO TBL_PREGUNTAS (NOMBRE_PREGUNTAS)Values ('¿DONDE NACISTE?'),('¿COMO SE LLAMA TU PERRO?'),('¿NOMBRE DE MARCA DE TUS TENNIS FAVORITAS?'),('¿NOMBRE DE TU MADRE?'),
('¿NOMBRE DE TU PADRE'),('¿NOMBRE DE TU EX?'),('¿COMO SE LLAMA TU PERSONAJE FAVORITO?')

CREATE TABLE TBL_CARRERAS_TECNICAS(
ID_CARRERA_TECNICA INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_CARRERA_TECNICA VARCHAR(200)NOT NULL UNIQUE,
DESCRIPCION_CARRERA_TECNICA VARCHAR(MAX) NOT NULL,
FOTO_CARRERA_TECNICA VARBINARY(MAX)
)

CREATE TABLE TBL_CLINICAS(
ID_CLINICAS INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_CLINICAS VARCHAR(100)NOT NULL UNIQUE
)
INSERT INTO TBL_CLINICAS(NOMBRE_CLINICAS) VALUES
    ('FOVIISTE'),('ISSTE'),('IMSS');

	SELECT * FROM TBL_CLINICAS

CREATE TABLE TBL_PAISES(
ID_PAIS INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_PAIS VARCHAR(250)NOT NULL UNIQUE,
FOTO_PAIS VARBINARY(MAX)
)
INSERT INTO TBL_PAISES(NOMBRE_PAIS)VALUES('MEXICO')

CREATE TABLE TBL_ESTADOS(
ID_ESTADO INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_ESTADO VARCHAR(250)NOT NULL UNIQUE,
FOTO_ESTADO VARBINARY(MAX)
)
INSERT INTO TBL_ESTADOS (NOMBRE_ESTADO) VALUES
('AGUASCALIENTES'),
('BAJA CALIFORNIA'),
('BAJA CALIFORNIA SUR'),
('CAMPECHE'),
('CHIAPAS'),
('CHIHUAHUA'),
('CIUDAD DE MÉXICO / DISTRITO FEDERAL'),
('COAHUILA'),
('COLIMA'),
('DURANGO'),
('ESTADO DE MÉXICO'),
('GUANAJUATO'),
('GUERRERO'),
('HIDALGO'),
('JALISCO'),
('MICHOACÁN'),
('MORELOS'),
('NAYARIT'),
('NUEVO LEÓN'),
('OAXACA'),
('PUEBLA'),
('QUERÉTARO'),
('QUINTANA ROO'),
('SAN LUIS POTOSÍ'),
('SINALOA'),
('SONORA'),
('TABASCO'),
('TAMAULIPAS'),
('TLAXCALA'),
('VERACRUZ'),
('YUCATÁN'),
('ZACATECAS');


CREATE TABLE TBL_RELACION_FAMILIAR(
ID_RELACION_FAMILIAR INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_RELACION_FAMILIAR VARCHAR(50) NOT NULL UNIQUE
)
INSERT INTO TBL_RELACION_FAMILIAR (NOMBRE_RELACION_FAMILIAR) VALUES
('Padre'),
('Madre'),
('Hermano'),
('Hermana'),
('Abuelo'),
('Abuela'),
('Tío'),
('Tía'),
('Primo'),
('Prima'),
('Cuñado'),
('Cuñada'),
('Suegro'),
('Suegra');

CREATE TABLE TBL_MOTIVO_CREDENCIAL(
ID_MOTIVO_CREDENCIAL INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_MOTIVO_CREDENCIAL VARCHAR(50)NOT NULL UNIQUE
)

INSERT INTO TBL_MOTIVO_CREDENCIAL (NOMBRE_MOTIVO_CREDENCIAL)VALUES('EXTRAVIO'),('CADUCIDAD'),('MALAS CONDICIONES')

CREATE TABLE TBL_CARRUSEL_IMG(
ID_CARRUSEL INT IDENTITY(1,1) PRIMARY KEY,
CARRUSEL VARBINARY(MAX)
)


CREATE TABLE TBL_MENSAJES_CONTACTOS(
ID_MENSAJE_CONTACTO INT IDENTITY(1,1)PRIMARY KEY,
NOMBRE_MENSAJE_CONTACTO VARCHAR(50) NOT NULL,
CORREO_MENSAJE_CONTACTO VARCHAR(50)NOT NULL,
MOTIVO_MENSAJE_CONTACTO TEXT,
FECHA_MENSAJE DATETIME
)

/*--------------------------------------------------------TABLAS CON ENLACES DE FOREING KEY*/
	CREATE TABLE TBL_USUARIOS (
    ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE_USUARIO VARCHAR(100) NOT NULL,
    APP_USUARIO VARCHAR(100) NOT NULL,
    APM_USUARIO VARCHAR(100),
    FECHA_NACIMIENTO_USUARIO DATETIME,
    TOKEN_USUARIO VARCHAR(8)not null,
    CORREO_USUARIO VARCHAR(50) UNIQUE NOT NULL,
    PWD_USUARIO VARCHAR(20) NOT NULL,
    PHONE_USUARIO BIGINT, 
	IP_USUARIO varchar(50)not null,
    IDRol INT,
    IDSexo INT,
	IDCuentaActivo int,
	IDPregunta int,
	RespuestaPregunta VARCHAR(255),
	FOREIGN KEY (IDRol) REFERENCES TBL_TIPO_ROL(ID_TIPO_ROL),
    FOREIGN KEY (IDSexo) REFERENCES TBL_SEXOS(ID_SEXOS),
	FOREIGN KEY (IDCuentaActivo) REFERENCES TBL_ACTIVOS_CUENTA (ID_ACTIVOS_CUENTA),
	FOREIGN KEY (IDPregunta) REFERENCES TBL_PREGUNTAS (ID_PREGUNTAS),
 FOTO_USUARIO VARBINARY(MAX)
);

	CREATE TABLE TBL_DOCENTES(
	ID_DOCENTES INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE_DOCENTES VARCHAR(50) NOT NULL,
	APP_DOCENTES VARCHAR(50) NOT NULL,
	APM_DOCENTES VARCHAR(50) NOT NULL,
	FECHA_NACIMIENTO_DOCENTES DATETIME NOT NULL,
	NOCONTTROL_DOCENTES BIGINT NOT NULL UNIQUE,
	TELEFONO_DOCENTES BIGINT NOT NULL UNIQUE,
	FOTO_DOCENTES VARBINARY(MAX),
	SEGURO_SOCIAL_DOCENTES BIGINT UNIQUE NOT NULL,
	IDSEXO INT,
    IDUSUARIO INT ,
	IDCLINICA INT,
	FOREIGN KEY (IDSEXO) REFERENCES TBL_SEXOS(ID_SEXOS),
    FOREIGN KEY (IDUSUARIO) REFERENCES TBL_USUARIOS(ID_USUARIO),
	FOREIGN KEY (IDCLINICA) REFERENCES TBL_CLINICAS(ID_CLINICAS),
)

	CREATE TABLE TBL_DOCENTES_TUTORADOS(
	ID_DOCENTE_TUTORADOS INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE_DOCENTE_TUTORADO VARCHAR(50) NOT NULL,

	)

CREATE TABLE TBL_ALUMNOS(
	ID_ALUMNOS INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE_ALUMNOS VARCHAR(100)NOT NULL,
	APP_ALUMNOS VARCHAR(100)NOT NULL,
	APM_ALUMNOS VARCHAR(100)NOT NULL,
	FOTO_ALUMNOS VARBINARY(MAX),
	FECHA_NACIMIENTO_ALUMNOS DATETIME NOT NULL,
	CURP_ALUMNOS VARCHAR(50)NOT NULL UNIQUE,
	NOCONTROL_ALUMNOS BIGINT NOT NULL UNIQUE,
	TELEFONO_ALUMNOS BIGINT NOT NULL UNIQUE,
	SEGURO_SOCIAL_ALUMNOS BIGINT NOT NULL UNIQUE,
	CUENTACREDENCIAL_ALUMNOS VARCHAR(2) NOT NULL,
	IDSEXO INT,
	FOREIGN KEY (IDSEXO) REFERENCES TBL_SEXOS(ID_SEXOS),
	IDUSUARIO INT,
	FOREIGN KEY (IDUSUARIO) REFERENCES  TBL_USUARIOS(ID_USUARIO),
	IDCLINICA INT,
	FOREIGN KEY (IDCLINICA) REFERENCES  TBL_CLINICAS(ID_CLINICAS),
	IDGRADO INT,
	FOREIGN KEY (IDGRADO) REFERENCES  TBL_GRADOS(ID_GRADO),
	IDGRUPO INT,
	FOREIGN KEY (IDGRUPO) REFERENCES  TBL_GRUPOS(ID_GRUPOS),
	IDTRASLADO INT,
	FOREIGN KEY (IDTRASLADO) REFERENCES  TBL_TRASLADO(ID_TRASLADO),
	IDTRASLADOTRANSPORTE INT,
	FOREIGN KEY (IDTRASLADOTRANSPORTE) REFERENCES  TBL_TRASLADO_TRANSPORTE(ID_TRASLADO_TRANSPORTE),
	IDCARRERATECNICA INT,
	FOREIGN KEY (IDCARRERATECNICA) REFERENCES  TBL_CARRERAS_TECNICAS(ID_CARRERA_TECNICA),
	IDPAIS INT,
	FOREIGN KEY (IDPAIS) REFERENCES  TBL_PAISES(ID_PAIS),
	IDESTADO INT,
	FOREIGN KEY (IDESTADO) REFERENCES  TBL_ESTADOS(ID_ESTADO),
	MUNICIPIO_ALUMNOS VARCHAR(100)NOT NULL,
	COMUNIDAD_ALUMNOS VARCHAR(100)NOT NULL,
	CALLE_ALUMNOS VARCHAR(100)NOT NULL,
	PROC_SEC_ALUMNO VARCHAR(100) NOT NULL,
		-- Campos adicionales para el familiar del alumno
	NOMBRE_COMPLETO_FAMILIAR VARCHAR(100) NOT NULL,
	TELEFONO_FAMILIAR BIGINT NOT NULL,
	TELEFONO_TRABAJO_FAMILIAR BIGINT NOT NULL,
	CORREO_FAMILIAR VARCHAR(100) NOT NULL
)

SELECT * FROM TBL_ALUMNOS

UPDATE TBL_ALUMNOS
SET 
    NOMBRE_COMPLETO_FAMILIAR = 'Andrea Martinez Perez',
    CORREO_FAMILIAR = 'andreamartpe@gmail.com',
    TELEFONO_FAMILIAR = 1234567890,
	TELEFONO_TRABAJO_FAMILIAR = 9994567890
WHERE 
    ID_ALUMNOS = 17;


CREATE TABLE TBL_MENSAJES_MOTIVO_CREDENCIAL(
ID_MENSAJES_MOTIVO_CREDENCIAL INT IDENTITY(1,1) PRIMARY KEY,
IDALUMNO INT,
FOREIGN KEY (IDALUMNO) REFERENCES  TBL_ALUMNOS(ID_ALUMNOS),
IDMOTIVO INT,
FOREIGN KEY (IDMOTIVO) REFERENCES  TBL_MOTIVO_CREDENCIAL(ID_MOTIVO_CREDENCIAL),
FECHA_MOTIVO_CREDENCIAL DATETIME
)

CREATE TABLE TBL_CREDENCIALES_ESCOLARES(
ID_CREDENCIAL_ESCOLAR INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_CREDENCIAL_ESCOLAR VARCHAR(100),
APP_CREDENCIAL_ESCOLAR VARCHAR(100),
APM_CREDENCIAL_ESCOLAR VARCHAR(100),
CARRERA_CREDENCIAL_ESCOLAR VARCHAR(100),
GRUPO_CREDENCIAL_ESCOLAR VARCHAR(2),
CURP_CREDENCIAL_ESCOLAR VARCHAR(22),
NOCONTROL_CREDENCIAL_ESCOLAR VARCHAR(22),
SEGSOCIAL_CREDENCIAL_ESCOLAR VARCHAR(22),
FOTO_CREDENCIAL_ESCOLAR VARBINARY(MAX),
IDALUMNOCREDE INT,
FOREIGN KEY (IDALUMNOCREDE) REFERENCES  TBL_ALUMNOS(ID_ALUMNOS),
)

-- ESTE VA PARTE DEL FRONTEND LA PAGINA PRINCIPAL
CREATE TABLE TBL_WELCOME(
ID_WELCOME INT IDENTITY(1,1) PRIMARY KEY,
WELCOME_TEXT TEXT,
FOTO_WELCOME  VARBINARY(MAX)
);
INSERT INTO TBL_WELCOME (WELCOME_TEXT)VALUES('El Centro de Bachillerato Tecnológico Agropecuario No. 5 inicia sus actividades el 02 de octubre de 1972 en la ciudad de Huejutla de Reyes Hidalgo, se encuentra localizado al norte de la ciudad, sobre el Boulevard Adolfo López Mateos s/n colonia aviación civil. Es un gra privilegio poder forjar a las futuras generaciones desde hace ya aproximadamente 50 años y de esta manera estar contribuyendo a nuestra comunidad, el C.B.T.A. 5 de Huejutla, Hgo. ha formado técnicos de calidad, con un claro compromiso social. ¡Bienvenidos!')


CREATE TABLE TBL_MISION(
ID_MISION INT IDENTITY(1,1)PRIMARY KEY,
MISION_TEXT TEXT
)
INSERT INTO TBL_MISION (MISION_TEXT)VALUES('Contribuir en la formación integral de individuos dotados de valores, conocimientos, habilidades y destrezas en el ámbito tecnológico y en el nivel bachillerato, que le permite incorporarse al trabajo productivo basado en competencias laborales como agente de cambio y /o continuar sus estudios en el nivel superior.')

CREATE TABLE TBL_VISION(
ID_VISION INT IDENTITY(1,1)PRIMARY KEY,
VISION_TEXT TEXT
)
INSERT INTO TBL_VISION (VISION_TEXT)VALUES
('Ser una institución educativa plenamente consolidada que represente una de las mejores opciones de educación tecnológica del nivel medio superior, donde la calidad sea el eje sobre el cual gire nuestra casa de estudios.')

SELECT * FROM TBL_VISION
/*--------------------------------------------EMPIEZAN LAS BITACORAS Y LOS TRIGGERS*/
CREATE TABLE BITACORA_USUARIOS (
    ID_BITACORA INT IDENTITY(1,1) PRIMARY KEY,
    ID_USUARIO INT,
    NOMBRE_USUARIO VARCHAR(255),
    ACCION_REALIZADA VARCHAR(MAX),
    DETALLES_ACCION VARCHAR(MAX),
    FECHA_ACCESO DATETIME,
    IP_ACCESO VARCHAR(50)
);

CREATE TABLE BITACORA_SESION (
    ID_SESION INT IDENTITY(1,1) PRIMARY KEY,
    ID_USUARIO INT,
    NOMBRE_USUARIO VARCHAR(255),
    CORREO_USUARIO VARCHAR(255),
    FECHA_INICIO DATETIME,
    IP_USUARIO VARCHAR(50),
    URL_SOLICITADA VARCHAR(255)
);

CREATE TABLE TBL_HORARIOS_ESCOLARES(
    ID_HORARIO INT IDENTITY(1,1) PRIMARY KEY,
    ID_ASIGNATURA INT NOT NULL,
    ID_DOCENTE INT NOT NULL,
    ID_GRADO INT NOT NULL,
    ID_GRUPO INT NOT NULL,
    ID_CARRERA_TECNICA INT NOT NULL,
    CICLO_ESCOLAR VARCHAR(10) NOT NULL,
	DIAS_HORARIOS VARCHAR(MAX),
    FOREIGN KEY (ID_ASIGNATURA) REFERENCES TBL_ASIGNATURAS(ID_ASIGNATURA),
    FOREIGN KEY (ID_DOCENTE) REFERENCES TBL_DOCENTES(ID_DOCENTES),
    FOREIGN KEY (ID_GRADO) REFERENCES TBL_GRADOS(ID_GRADO),
    FOREIGN KEY (ID_GRUPO) REFERENCES TBL_GRUPOS(ID_GRUPOS),
    FOREIGN KEY (ID_CARRERA_TECNICA) REFERENCES TBL_CARRERAS_TECNICAS(ID_CARRERA_TECNICA)
);

CREATE TABLE TBL_HORARIO_ALUMNOS (
    ID_HORARIO_ALUMNO INT IDENTITY(1,1) PRIMARY KEY,
    ID_HORARIO INT NOT NULL,
    ID_ALUMNO INT NOT NULL,
    FECHA_INSCRIPCION DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (ID_HORARIO) REFERENCES TBL_HORARIOS_ESCOLARES(ID_HORARIO),
    FOREIGN KEY (ID_ALUMNO) REFERENCES TBL_ALUMNOS(ID_ALUMNOS)
);

CREATE TABLE TBL_ASISTENCIAS (
    ID_ASISTENCIA INT IDENTITY(1,1) PRIMARY KEY,
    ID_ALUMNO INT NOT NULL,
    ID_HORARIO INT NOT NULL,
    FECHA DATETIME NOT NULL,
    ESTADO_ASISTENCIA VARCHAR(50) NOT NULL,
    COMENTARIOS VARCHAR(MAX),
    FOREIGN KEY (ID_ALUMNO) REFERENCES TBL_ALUMNOS(ID_ALUMNOS),
    FOREIGN KEY (ID_HORARIO) REFERENCES TBL_HORARIOS_ESCOLARES(ID_HORARIO)
);

CREATE TABLE TBL_ACTIVIDADES_NOTICIAS(
ID_ACTIVIDADES_NOTICIAS INT IDENTITY(1,1) PRIMARY KEY,
IMAGEN_ACTIVIDAD_NOTICIA VARBINARY(MAX) NOT NULL,
TITULO_ACTIVIDAD_NOTICIA VARCHAR(20) NOT NULL,
DESCRIPCION_ACTIVIDAD_NOTICIA TEXT NOT NULL,
FECHA_ACTIVIDAD_NOTICIAS DATETIME
)

CREATE TABLE TBL_INFO_INSCRIPTION(
ID_INFO_INSCRIPTION INT IDENTITY(1,1) PRIMARY KEY,
TXT_INFO_INSCRIPTION TEXT,
REQUERIMENTS_INFO_INSCRIPTION TEXT,
PERIODO_INFO_INSCRIPCION TEXT,
IMAGEN_INFO_INSCRIPTION VARBINARY(MAX) 
)


CREATE TABLE TBL_ACTIVIDADES_CULTURALES(
ID_ACTIVIDAD_CULTURAL INT IDENTITY(1,1) PRIMARY KEY,
IMAGEN_ACTIVIDAD_CULTURAL VARBINARY(MAX),
NOMBRE_ACTIVIDAD_CULTURAL TEXT,
DESCRIPCION_ACTIVIDAD_CULTURAL TEXT
)

CREATE TABLE TBL_SOBRE_NOSOTROS(
ID_SOBRE_NOSOTROS INT IDENTITY(1,1) PRIMARY KEY,
TXT_SOBRE_NOSOTROS TEXT,
IMAGEN_SOBRE_NOSOTROS VARBINARY(MAX),
FECHA_SOBRE_NOSOTROS DATETIME
)

CREATE TABLE TBL_INFO_BECAS(
ID_INFO_BECAS INT IDENTITY(1,1) PRIMARY KEY,
TITULO_INFO_BECAS VARCHAR(20),
DESCRIPCION_INFO_BECAS TEXT,
REQUISITOS_INFO_BECAS TEXT,
FOTO_INFO_BECAS VARBINARY(MAX)
)

CREATE TABLE TBL_NOTIFICACIONES(
ID_NOTIFICACIONES INT IDENTITY(1,1) PRIMARY KEY,
ALUMNO_ID INT NOT NULL,
FOREIGN KEY (ALUMNO_ID) REFERENCES TBL_ALUMNOS(ID_ALUMNOS),
SUBJECT_NOTIFICACION  TEXT,
MESSAGE_NOTIFICACION TEXT,
FECHA_NOTIFICACIONES DATETIME
)

CREATE TABLE TBL_NOTIFICACIONES_DOCENTES(
ID_NOTIFICACIONES_DOCENTES INT IDENTITY(1,1) PRIMARY KEY,
DOCENTE_ID INT NOT NULL,
FOREIGN KEY (DOCENTE_ID) REFERENCES TBL_DOCENTES(ID_DOCENTES),
SUBJECT_NOTIFICACION_DOC  TEXT,
MESSAGE_NOTIFICACION_DOC TEXT,
FECHA_NOTIFICACIONES_DOC DATETIME
)

INSERT INTO TBL_NOTIFICACIONES_DOCENTES 
(DOCENTE_ID, SUBJECT_NOTIFICACION_DOC, MESSAGE_NOTIFICACION_DOC, FECHA_NOTIFICACIONES_DOC)
VALUES 
(7, 'Aviso de Reunión', 'Estimado docente, le recordamos la reunión programada para mañana a las 10:00 AM.', GETDATE());

SELECT * FROM TBL_NOTIFICACIONES_DOCENTES
SELECT * FROM TBL_ALUMNOS
SELECT * FROM TBL_DOCENTES
SELECT * FROM TBL_USUARIOS

CREATE TABLE TBL_ALUMNOS_AGREGADOS(
ID_ALUMNOS_AGREGADOS INT IDENTITY(1,1)PRIMARY KEY,
ID_USUARIO INT,
FOREIGN KEY (ID_USUARIO) REFERENCES  TBL_USUARIOS(ID_USUARIO),
ID_ALUMNO INT,
FOREIGN KEY (ID_ALUMNO) REFERENCES  TBL_ALUMNOS(ID_ALUMNOS)
)

select * from TBL_USUARIOS
select * from TBL_ALUMNOS_AGREGADOS


CREATE TABLE TBL_SOLICITANTES (
    ID_SOLICITANTE INT IDENTITY(1,1) PRIMARY KEY,
    FICHA_NO VARCHAR(50) NOT NULL,
    APELLIDO_PATERNO VARCHAR(100) NOT NULL,
    APELLIDO_MATERNO VARCHAR(100) NOT NULL,
    NOMBRES VARCHAR(100) NOT NULL,
    FOTO VARBINARY(MAX),
    DIRECCION VARCHAR(250) NOT NULL,
    LOCALIDAD VARCHAR(100) NOT NULL,
    MUNICIPIO VARCHAR(100) NOT NULL,
    EDAD INT NOT NULL,
    PROMEDIO_SEC DECIMAL(3,2) NOT NULL,
    FECHA_NACIMIENTO DATETIME NOT NULL,
    BECA BIT NOT NULL,
    TIPO_DISCAPACIDAD VARCHAR(100),
    HABLANTE_LENGUA_INDIGENA BIT NOT NULL,
    CORREO_ELECTRONICO VARCHAR(100) NOT NULL,
    ESCUELA_PROCEDENCIA VARCHAR(100) NOT NULL,
    CCT VARCHAR(50),
    TIPO_SECUNDARIA VARCHAR(50),
    DIRECCION_SECUNDARIA VARCHAR(250),
    LOCALIDAD_SECUNDARIA VARCHAR(100),
    MUNICIPIO_SECUNDARIA VARCHAR(100),
    ESTADO_SECUNDARIA VARCHAR(100),
    NOMBRE_PADRE_TUTOR VARCHAR(100) NOT NULL,
    ID_RELACION_FAMILIAR INT, -- Nueva columna para la relación familiar
    TELEFONO_ALUMNO BIGINT,
    TELEFONO_TUTOR BIGINT,
    TELEFONO_FAMILIAR BIGINT,
    ID_CARRERA_TECNICA INT, -- Nueva columna para la carrera técnica
    ID_INFO_BECAS INT, -- Nueva columna para la beca
    FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (ID_RELACION_FAMILIAR) REFERENCES TBL_RELACION_FAMILIAR(ID_RELACION_FAMILIAR),
    FOREIGN KEY (ID_CARRERA_TECNICA) REFERENCES TBL_CARRERAS_TECNICAS(ID_CARRERA_TECNICA),
    FOREIGN KEY (ID_INFO_BECAS) REFERENCES TBL_INFO_BECAS(ID_INFO_BECAS)
);

select * from TBL_ALUMNOS

select * from TBL_USUARIOS

CREATE TABLE TBL_REGISTRO_ACCESO_DOCENTE (
    id_registro INT IDENTITY(1,1) PRIMARY KEY,  -- Columna de clave primaria con incremento automático
    ID_DOCENTE INT NOT NULL,                    -- Columna para almacenar el ID del docente
    nombre_docente NVARCHAR(255) NOT NULL,      -- Columna para almacenar el nombre completo del docente
    fecha_registro_acceso DATETIME NOT NULL,   
	codigo_qr varchar(255)NOT NULL, -- Columna para almacenar la fecha y hora de acceso
    FOREIGN KEY (ID_DOCENTE) REFERENCES TBL_DOCENTES(ID_DOCENTES)  -- Llave foránea referenciando a la tabla de docentes
);

CREATE TABLE TBL_REGISTRO_ACCESO_ALUMNO (
    id_registro_alumno INT IDENTITY(1,1) PRIMARY KEY,  -- Columna de clave primaria con incremento automático
    ID_ALUMNOX INT NOT NULL,                    -- Columna para almacenar el ID del docente
    nombre_alumnox NVARCHAR(255) NOT NULL,      -- Columna para almacenar el nombre completo del docente
    fecha_registro_acceso_alumno DATETIME NOT NULL,   
	codigo_qr_alumno varchar(255)NOT NULL, -- Columna para almacenar la fecha y hora de acceso
    FOREIGN KEY (ID_ALUMNOX) REFERENCES TBL_ALUMNOS(ID_ALUMNOS)  -- Llave foránea referenciando a la tabla de docentes
);

SELECT * FROM TBL_REGISTRO_ACCESO_ALUMNO

CREATE TABLE TBL_FEEDBACK (
    ID_FEEDBACK INT IDENTITY(1,1) PRIMARY KEY,  -- ID de la tabla con autoincremento
    IDUSUARIO INT NOT NULL,                     -- ID de usuario referenciado
    EMOCION_FEEDBACK VARCHAR(30),               -- Emoción del feedback (cadena de texto con longitud de 30)
    MOTIVO_FEEDBACK TEXT,                       -- Motivo del feedback (texto)
    FOREIGN KEY (IDUSUARIO) REFERENCES TBL_USUARIOS(ID_USUARIO)  -- Relación con la tabla de usuarios
);

SELECT * FROM TBL_FEEDBACK
